### ISSUE TITLE
Error When Song Loading After Using Change Keys In Pause Menu

### ISSUE THREAD

**Issue by BlueColorsin** [BeastlyGhost/FNF-Funkin-Feather#10]
### Describe the bug

overall the Chart Placement system kinda fucks up when you use the Change key setting in the pause menu and then go back to resume song

only happens after the function is called 3 times as seen in the gif
and then is stays fucked up until restart song is used

it fucks up for the first 2-3 secs and then goes back to normal
![Funkin-Feather_GD7zNCOtsf-min](https://user-images.githubusercontent.com/76269429/207668575-9e8a9f90-8257-40fb-b7ed-ad0c2b08a828.gif)

### Have you modified the engine in any way prior to reporting this bug?

No

### If you have selected 'Yes' in the previous field, describe what you modified within your build of the engine

Lmao it made me type in here

### Provide the log that the terminal outputs
Normal Chart Json Parcening output as normal

**Comment by BeastlyGhost** [comment]
![image](https://user-images.githubusercontent.com/45212377/207683706-ade429f4-78a0-4bc9-a6f8-7d6e87d333df.png)
fixed, gonna push it shortly
