### ISSUE TITLE
Compiling Problems again lmao 

### ISSUE THREAD

**Issue by BlueColorsin** [BeastlyGhost/FNF-Funkin-Feather#3]
![image](https://user-images.githubusercontent.com/76269429/205465029-50fee06f-8091-4b1b-b22e-b8345dc4fac5.png)

**Comment by MemeHoovy** [comment]
I'm pretty sure the engine ain't finished bruh

**Comment by BeastlyGhost** [comment]
fixed

**Comment by BlueColorsin** [comment]
thanks
